%YAML 1.1
---

#### Main Role Configuration ####

kafka_image: "tfplenum/kafka"
kafka_port: 9092
kafka_ver: alpine
kafka_dir: "{{ install_dir }}/kafka"
kafka_data_path: "/data/kafka"
kafka_pv_size: 1
kafka_home: /opt/kafka
kafka_jmx_port: "9999"

zookeeper_port: 2181
zookeeper_dir: "{{ install_dir }}/zookeeper"
zookeeper_data_path: "/data"
zookeeper_datalog_path: "/datalog"
zookeeper_pv_size: 1
zookeeper_image: tfplenum/zookeeper
zookeeper_ver: alpine
zookeeper_home: /opt/zookeeper

# The num.io.threads property should be set to a value equal to or greater than
# the number of disks dedicated for Kafka. Recommendation: start by setting this
# property equal to the number of disks.
num_of_pvcs: 1
