#######################################################
###################  Kubernetes Setup Nodes ###############
#######################################################
---

- import_tasks: 00_preflight.yml

- name: Install New Node
  block:
    - import_tasks: 05_install.yml
    - import_tasks: 10_remote_sensor.yml
  when: (kube_reload is defined and kube_reload) or (kube_check_result is defined and kube_check_result.stdout == "")

- name: Label master node with appropriate roles
  import_role:
    name: kubernetes/common
    tasks_from: label_nodes.yml

- name: Setup DNS
  import_role:
    name: kubernetes/common
    tasks_from: setup_kubedns
...
